# Generated by Django 6.1 on 2026-09-27 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('almacenamiento', models.CharField(max_length=50, verbose_name='Almacenamiento')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('imagen', models.CharField(max_length=255, verbose_name='Ruta de Imagen')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolas', to='consolasApp.marca')),
            ],
            options={
                'verbose_name': 'Consola',
                'verbose_name_plural': 'Consolas',
            },
        ),
    ]
