# Generated by Django 6.1 on 2026-09-27 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consolasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Nombre del Accesorio')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo (Ej: Audio, Mando)')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('imagen', models.CharField(max_length=255, verbose_name='Ruta de Imagen')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorios', to='consolasApp.marca')),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
            },
        ),
    ]
