# Generated by Django 6.1 on 2026-09-27 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Plataforma')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Juego')),
                ('genero', models.CharField(max_length=50, verbose_name='Género')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('imagen', models.CharField(max_length=255, verbose_name='Ruta de Imagen (Ej: img/juego.jpg)')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='inventariojuegoApp.plataforma')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
    ]
